title: Saavutettava.dev
default_lang: fi
author:
  name: 'Kalle Lahtinen'
  email: null
taxonomies:
  - category
  - tag
metadata:
  Kuvaus: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
